testing:
  sampling:
    measurements_count: 0  # if lower then 1 will not use
    total_duration_seconds: 1  # if lower then 0 will not use
    sampling_frequency_hz: 1

ammeters:
 greenlee:
   port: 5000
   command: "MEASURE_GREENLEE -get_measurement"
 entes:
   port: 5001
   command: "MEASURE_ENTES -get_data"
 circutor:
   port: 5002
   command: "MEASURE_CIRCUTOR -get_measurement -current"

analysis:
  statistical_metrics:
  visualization:
    enabled: false  # will show every plot (stop tests until plot is closed)
    plot_types: ["line", "scatter", "hist"]
    default_figure:
      figure_size: [8, 5]
      default_plot_type: "line"

result_management:
  folder_name: results
